

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: ${DB_CONN_TIMEOUT:20000}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000}
      # In production, leak detection is typically disabled (0)
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:0}

  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: ${JPA_FORMAT_SQL:false}
        use_sql_comments: ${JPA_USE_SQL_COMMENTS:false}
        jdbc:
          time_zone: ${JDBC_TIME_ZONE:Asia/Seoul}

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE:health,info}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

logging:
  level:
    root: ${APP_LOG_LEVEL:INFO}
    org.hibernate.SQL: ${LOG_SQL_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_BINDER_LEVEL:WARN}
    com.example.stockkkkk: ${APP_LOG_LEVEL:INFO} # change to your base package if different
  file:
    name: ${LOG_FILE:}    # e.g. /var/log/app/app.log
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:10MB}
      max-history: ${LOG_MAX_HISTORY:7}
